# Dot at end of line makes it clearer that the line is not done
Layout/DotPosition:
  EnforcedStyle: trailing

# Spec blocks can be any size
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Require lines to fit in pull requests.
Metrics/LineLength:
  Max: 92

# Prefer oroginal RuboCop defaults
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%W': ()
    '%w': ()
