inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'tmp/**/*'
  TargetRubyVersion: 2.4

# Dot at end of line makes it clearer that the line is not done
Layout/DotPosition:
  EnforcedStyle: trailing

# Spec blocks can be any size
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Lenient line length
Metrics/LineLength:
  Max: 92

# DNote namespace is mapped to dnote directory, both in lib and spec.
RSpec/FilePath:
  CustomTransform:
    DNote: dnote

Style/NumericPredicate:
  EnforcedStyle: comparison

# Prefer original RuboCop defaults
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%W': ()
    '%w': ()
