---
language: ruby

cache:
  bundler: true

script: bundle exec rake

jobs:
  include:
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: jruby-9.2
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rubinius-4
    - rvm: 2.7.1
      script: bundle exec rubocop
  allow_failures:
    - rvm: jruby-9.2
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rubinius-4

branches:
  only:
    - master
    - auto-update-dependencies
