sudo: required
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.1.16.0
  - jruby-head
  - ruby-head
  - rubinius-3
matrix:
  allow_failures:
    - rvm: jruby-9.1.16.0
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rubinius-3
script: "bundle exec rake"
branches:
  only:
    - master
